version: '3.7'
services:
  web:
    image: nginx:alpine
    depends_on:
      - vue
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/www/:/var/www
      - ./web/nginx/conf.d/:/etc/nginx/conf.d/
  vue:
    build:
      context: ./vue/
      target: 'build-stage'
    restart: always
    volumes:
    - './vue/app:/app'
    command: npm run build
  backend:
    build:
      context: ./backend/
      target: 'build-stage'
    ports:
      - "6969:6969"
    command: /app/src/smartwater-server